sudo: false
language: php
php:
- '5.6'
- '5.5'
- '5.4'

before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install bower
  - npm install gulp

install: 
  - composer install --no-dev --no-scripts --quiet --optimize-autoloader
  - npm install --silent --no-spin -p ./web/app/themes/ado-theme/
  - bower install --config.cwd="./web/app/themes/ado-theme/"
  - gulp --production --cwd ./web/app/themes/ado-theme/

script:
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,vendor/ -n -s .
